//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLinView.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLinView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ApplicationExit {
            get {
                object obj = ResourceManager.GetObject("ApplicationExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Connect {
            get {
                object obj = ResourceManager.GetObject("Connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FileNew {
            get {
                object obj = ResourceManager.GetObject("FileNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FileOpen {
            get {
                object obj = ResourceManager.GetObject("FileOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FileSave {
            get {
                object obj = ResourceManager.GetObject("FileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FileSaveAs {
            get {
                object obj = ResourceManager.GetObject("FileSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FrameNew {
            get {
                object obj = ResourceManager.GetObject("FrameNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap HelpAbout {
            get {
                object obj = ResourceManager.GetObject("HelpAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap HelpContents {
            get {
                object obj = ResourceManager.GetObject("HelpContents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap LINReset {
            get {
                object obj = ResourceManager.GetObject("LINReset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PubText {
            get {
                object obj = ResourceManager.GetObject("PubText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RcvText {
            get {
                object obj = ResourceManager.GetObject("RcvText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 PLin-View 的本地化字符串。
        /// </summary>
        internal static string SAppCaption {
            get {
                return ResourceManager.GetString("SAppCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLin-View - Error 的本地化字符串。
        /// </summary>
        internal static string SAppCaptionError {
            get {
                return ResourceManager.GetString("SAppCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLin-View - [{0}] 的本地化字符串。
        /// </summary>
        internal static string SAppCaptionFileName {
            get {
                return ResourceManager.GetString("SAppCaptionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLin-View - Information 的本地化字符串。
        /// </summary>
        internal static string SAppCaptionInfo {
            get {
                return ResourceManager.GetString("SAppCaptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLin-View - Question 的本地化字符串。
        /// </summary>
        internal static string SAppCaptionQuestion {
            get {
                return ResourceManager.GetString("SAppCaptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current selected hardware mode and the hardware mode loading from file &quot;{0}&quot; are different. Do you want to change the hardware mode of the current connection? 的本地化字符串。
        /// </summary>
        internal static string SDifferentHwModes {
            get {
                return ResourceManager.GetString("SDifferentHwModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Empty&gt; 的本地化字符串。
        /// </summary>
        internal static string SEmpty {
            get {
                return ResourceManager.GetString("SEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:d} Bit/sec 的本地化字符串。
        /// </summary>
        internal static string SFormatBaudrate {
            get {
                return ResourceManager.GetString("SFormatBaudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Frame Definitions selected 的本地化字符串。
        /// </summary>
        internal static string SFrameEntriesCombo {
            get {
                return ResourceManager.GetString("SFrameEntriesCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Definition &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string SFrameEntryCombo {
            get {
                return ResourceManager.GetString("SFrameEntryCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit frame 的本地化字符串。
        /// </summary>
        internal static string SFramesDlgEditCaption {
            get {
                return ResourceManager.GetString("SFramesDlgEditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New frame 的本地化字符串。
        /// </summary>
        internal static string SFramesDlgNewCaption {
            get {
                return ResourceManager.GetString("SFramesDlgNewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master 的本地化字符串。
        /// </summary>
        internal static string SHardwareModeMaster {
            get {
                return ResourceManager.GetString("SHardwareModeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string SHardwareModeNone {
            get {
                return ResourceManager.GetString("SHardwareModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slave 的本地化字符串。
        /// </summary>
        internal static string SHardwareModeSlave {
            get {
                return ResourceManager.GetString("SHardwareModeSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;No hardware found&gt; 的本地化字符串。
        /// </summary>
        internal static string SHardwareNothingFound {
            get {
                return ResourceManager.GetString("SHardwareNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCAN-USB Pro 的本地化字符串。
        /// </summary>
        internal static string SHardwareTypeLIN {
            get {
                return ResourceManager.GetString("SHardwareTypeLIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string SHardwareTypeUnkown {
            get {
                return ResourceManager.GetString("SHardwareTypeUnkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected to {0} ({1}) 的本地化字符串。
        /// </summary>
        internal static string SLINConnectTo {
            get {
                return ResourceManager.GetString("SLINConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel: {0} 的本地化字符串。
        /// </summary>
        internal static string SLINConnectToCh {
            get {
                return ResourceManager.GetString("SLINConnectToCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode: Master 的本地化字符串。
        /// </summary>
        internal static string SLINModeMaster {
            get {
                return ResourceManager.GetString("SLINModeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode: Not Initialized 的本地化字符串。
        /// </summary>
        internal static string SLINModeNotInit {
            get {
                return ResourceManager.GetString("SLINModeNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode: Slave 的本地化字符串。
        /// </summary>
        internal static string SLINModeSlave {
            get {
                return ResourceManager.GetString("SLINModeSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not connected 的本地化字符串。
        /// </summary>
        internal static string SLINNotConnected {
            get {
                return ResourceManager.GetString("SLINNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware: Not Initialized 的本地化字符串。
        /// </summary>
        internal static string SLINStatusNotInit {
            get {
                return ResourceManager.GetString("SLINStatusNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overruns: {0} 的本地化字符串。
        /// </summary>
        internal static string SLINStatusOverruns {
            get {
                return ResourceManager.GetString("SLINStatusOverruns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bus: Active 的本地化字符串。
        /// </summary>
        internal static string SLINStausActive {
            get {
                return ResourceManager.GetString("SLINStausActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware: Baudrate Detection 的本地化字符串。
        /// </summary>
        internal static string SLINStausBaudDetect {
            get {
                return ResourceManager.GetString("SLINStausBaudDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bus-Line: Shorted Ground 的本地化字符串。
        /// </summary>
        internal static string SLINStausShortGround {
            get {
                return ResourceManager.GetString("SLINStausShortGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bus: Sleep 的本地化字符串。
        /// </summary>
        internal static string SLINStausSleep {
            get {
                return ResourceManager.GetString("SLINStausSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Publish 的本地化字符串。
        /// </summary>
        internal static string SMMPublish {
            get {
                return ResourceManager.GetString("SMMPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Transmit 的本地化字符串。
        /// </summary>
        internal static string SMMTransmit {
            get {
                return ResourceManager.GetString("SMMTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 O.k. 的本地化字符串。
        /// </summary>
        internal static string SOk {
            get {
                return ResourceManager.GetString("SOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open PLin-View file... 的本地化字符串。
        /// </summary>
        internal static string SOpenCaption1 {
            get {
                return ResourceManager.GetString("SOpenCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLin frame files (*.lin)|*.lin 的本地化字符串。
        /// </summary>
        internal static string SOpenFilter1 {
            get {
                return ResourceManager.GetString("SOpenFilter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLIN_Monitor 的本地化字符串。
        /// </summary>
        internal static string SPLinClientName {
            get {
                return ResourceManager.GetString("SPLinClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No LIN-frame received. 的本地化字符串。
        /// </summary>
        internal static string SToolTipRcvNoEntry {
            get {
                return ResourceManager.GetString("SToolTipRcvNoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No LIN-frame defined to transmit or to publish. 的本地化字符串。
        /// </summary>
        internal static string SToolTipXmtNoEntry {
            get {
                return ResourceManager.GetString("SToolTipXmtNoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap XmtText {
            get {
                object obj = ResourceManager.GetObject("XmtText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
